trigger:
  branches:
    include:
      - main  # Change this to your default branch

pool:
  vmImage: 'windows-latest'  # Use the latest Windows image provided by Microsoft

steps:
  - task: DotNetCoreCLI@2
    displayName: 'Restore Dependencies'
    inputs:
      command: 'restore'
      projects: '**/*.csproj'  # Adjust if your project file is in a specific location

  - task: DotNetCoreCLI@2
    displayName: 'Build Application'
    inputs:
      command: 'build'
      projects: '**/*.csproj'

  - task: DotNetCoreCLI@2
    displayName: 'Run Tests'
    inputs:
      command: 'test'
      projects: '**/*.csproj'